/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.transistor.app.ui;

import com.transistor.app.lib.CONST;
import com.transistor.app.lib.ReadTransistorData;
import java.io.File;
import java.util.List;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author xizuth
 */
public class DataTrasistorWindow extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DataTrasistorWindow.class.getName());

    /**
     * Creates new form NewJDialog
     */
    public DataTrasistorWindow(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        loadData();
    }

    private void loadData() {

        File fileLocal = new File(CONST.FILE_LOCAL);

        if (fileLocal.exists()) {
            ReadTransistorData rd = new ReadTransistorData(fileLocal.getAbsolutePath());
            txtPathData.setText(fileLocal.getAbsolutePath());

            StringBuilder st = new StringBuilder();
            List<List<String>> rows = rd.getData();

            st.append(rows.get(0)).append("\n");
            st.append("--------------------------\n");

            for (int i = 1; i < rows.size(); i++) {
                st.append(rows.get(i)).append("\n");
            }

            areaData.setText(st.toString());
        }else{
            
            String st = 
                    "EJEMPLO DE ARCHIVO CSV PARA ALMACENAR DATOS \n" +
                    "| name    | hfe  | VCE_sat |VBE_sat|\n" +
                    "| 2N2222A | 35   | 0.5     |0.6    |\n" +
                    "| 2N3904  | 100  | 0.2     |0.65   |\n";
            areaData.setText(st);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaData = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        txtPathData = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Datos de transistores");

        jLabel1.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Datos de transistores");

        areaData.setEditable(false);
        areaData.setColumns(20);
        areaData.setFont(new java.awt.Font("RobotoMono Nerd Font", 0, 18)); // NOI18N
        areaData.setRows(5);
        jScrollPane1.setViewportView(areaData);

        jButton1.setFont(new java.awt.Font("sansserif", 1, 13)); // NOI18N
        jButton1.setText("Cargar datos ...");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        txtPathData.setEditable(false);
        txtPathData.setText("Path...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 516, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(txtPathData)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPathData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            JFileChooser chooser = new JFileChooser(".");

            int result = chooser.showOpenDialog(this);

            if (result == JFileChooser.APPROVE_OPTION) {
                ReadTransistorData rd = new ReadTransistorData(chooser.getSelectedFile().getAbsolutePath());

                txtPathData.setText(chooser.getSelectedFile().getAbsolutePath());

                StringBuilder st = new StringBuilder();
                List<List<String>> rows = rd.getData();

                st.append(rows.get(0)).append("\n");
                st.append("--------------------------\n");

                for (int i = 1; i < rows.size(); i++) {
                    st.append(rows.get(i)).append("\n");
                }

                areaData.setText(st.toString());
                ReadTransistorData.saveData(rows);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error al cargar los datos");
            e.printStackTrace();
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                DataTrasistorWindow dialog = new DataTrasistorWindow(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaData;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtPathData;
    // End of variables declaration//GEN-END:variables
}
