/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.temperature.app;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author xizuth
 */
public class MainWindow extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainWindow.class.getName());

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
        //aqui se agrupan los radios
        buttonGroup1.add(radioCelsius);
        buttonGroup1.add(radioFahrenheit);
        buttonGroup1.add(radioKelvin);
        changeComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        radioCelsius = new javax.swing.JRadioButton();
        radioFahrenheit = new javax.swing.JRadioButton();
        radioKelvin = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        inputData = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        btnCalculate = new javax.swing.JToggleButton();
        labelResult = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Convertidor Temperatura");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("JetBrains Mono", 1, 36)); // NOI18N
        jLabel1.setText("Convertidor de temperatura");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleccione"));
        jPanel1.setLayout(new java.awt.GridLayout());

        radioCelsius.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        radioCelsius.setText("Celsius");
        radioCelsius.addActionListener(this::radioCelsiusActionPerformed);
        jPanel1.add(radioCelsius);

        radioFahrenheit.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        radioFahrenheit.setSelected(true);
        radioFahrenheit.setText("Fahrenhiet");
        radioFahrenheit.addActionListener(this::radioFahrenheitActionPerformed);
        jPanel1.add(radioFahrenheit);

        radioKelvin.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        radioKelvin.setText("Kelvin");
        radioKelvin.addActionListener(this::radioKelvinActionPerformed);
        jPanel1.add(radioKelvin);

        inputData.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        inputData.setText("0");

        jComboBox1.setFont(new java.awt.Font("JetBrains Mono", 0, 14)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "°C", "°K" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inputData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCalculate.setFont(new java.awt.Font("JetBrains Mono", 1, 14)); // NOI18N
        btnCalculate.setText("CALCULAR");
        btnCalculate.addActionListener(this::btnCalculateActionPerformed);

        labelResult.setFont(new java.awt.Font("JetBrains Mono", 1, 48)); // NOI18N
        labelResult.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelResult.setText("-");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCalculate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCalculate)
                .addGap(18, 18, 18)
                .addComponent(labelResult, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalculateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalculateActionPerformed

        String combo = jComboBox1.getSelectedItem().toString();
        Temperature t = new Temperature();

        System.out.println(combo);
        String unit = "";
        if (radioFahrenheit.isSelected()) {
            double f = Double.parseDouble(inputData.getText());
            double resultado = 0;

            if (combo.endsWith("C")) {
                resultado = t.convertFahrenheitToCelsius(f);
                unit = "C";
            } else if (combo.endsWith("K")) {
                //aqui va la formula para convertir de F -> K
                resultado = t.convertFahrenheitToKelvin(f);
                unit = "K";
            }
            labelResult.setText(String.format("%.2f °%s", resultado, unit));

        } else if (radioCelsius.isSelected()) {
            double c = Double.parseDouble(inputData.getText());
            double resultado = 0;

            if (combo.endsWith("F")) {
                resultado = t.convertCelsiusToFahrenheit(c);
                unit = "F";
            } else if (combo.endsWith("K")) {
                resultado = t.convertCelsiusToKelvin(c);
                unit = "K";
            }

            labelResult.setText(String.format("%.2f °%s", resultado, unit));

        } else if (radioKelvin.isSelected()) {
            double k = Double.parseDouble(inputData.getText());
            double resultado = 0;

            if (combo.endsWith("C")) {
                resultado = t.convertKelvinToCelsius(k);
                unit = "C";

            } else if (combo.endsWith("F")) {
                resultado = t.convertKelvintoFahrenheit(k);
                unit = "F";
            }

            labelResult.setText(String.format("%.2f °%s", resultado, unit));

        }
    }//GEN-LAST:event_btnCalculateActionPerformed

    private void radioCelsiusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCelsiusActionPerformed
        // TODO add your handling code here:
        changeComboBox();
    }//GEN-LAST:event_radioCelsiusActionPerformed

    private void radioFahrenheitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioFahrenheitActionPerformed
        changeComboBox();
    }//GEN-LAST:event_radioFahrenheitActionPerformed

    private void radioKelvinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioKelvinActionPerformed
        changeComboBox();
    }//GEN-LAST:event_radioKelvinActionPerformed

    private void changeComboBox() {

        DefaultComboBoxModel<String> model = null;

        if (radioFahrenheit.isSelected()) {
            model = new DefaultComboBoxModel<>(new String[]{"°C", "°K"});
        } else if (radioCelsius.isSelected()) {
            model = new DefaultComboBoxModel<>(new String[]{"°F", "°K"});
        } else if (radioKelvin.isSelected()) {
            model = new DefaultComboBoxModel<>(new String[]{"°C", "°F"});
        }

        jComboBox1.setModel(model);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnCalculate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField inputData;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelResult;
    private javax.swing.JRadioButton radioCelsius;
    private javax.swing.JRadioButton radioFahrenheit;
    private javax.swing.JRadioButton radioKelvin;
    // End of variables declaration//GEN-END:variables
}
